Rodina krasa_1
brivie-suni/startit-chats pull request #8
Opened 2020-02-19 20:06 UTC by Nrodina

Rodina krasa_1

2020-02-19 20:07 UTC, Nrodina commented
Rodina krasa_1

2020-02-25 20:59 UTC, GundegaDekena requested changes
Izmaiņas chats.py nav nepieciešamas un vajag atsaukt (uz iepriekšējo faila versiju)
stils.css varētu izmainīt vienu ciparu, lai pilnībā strādatu kā domāts

2020-02-25 20:59 UTC, GundegaDekena commented on chats.py
> +    / import colorama
Šīs izmaiņas šajā failā nevajag, python kods nav jāaiztiek šai funkcionalitātei. Un šī rindiņa radīs sintakses kļūdu

2020-02-25 20:59 UTC, GundegaDekena commented on static/stils.css
> +ul > li:nth-of-type(3n+1) {
Šiet vajadzētu `3n +2`, lai atšķirtos no sekojošās definīcijas, citādi krāsa tiek pārrrakstīta un netiks izmantota

2020-02-26 19:06 UTC, GundegaDekena approved these changes

2020-02-26 19:09 UTC, merged